version: "3.8"

volumes:
  data:

services: 
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  # postgres: 
  #   image: postgres
  #   restart: always
  #   ports:
  #     - "5430:5430"
  #   environment:
  #     DATABASE_HOST: 127.0.0.1
  #     POSTGRES_USER: "root"
  #     POSTGRES_PASSWORD: "root"
  #     POSTGRES_DB: taskdb
  #   volumes:
  #     - data:/var/lib/postgresql/data
  
  # pgamdin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #   ports: 
  #     - "80:80"
  #   depends_on:
  #     - postgres
networks:
  default:
    driver: bridge
