DROP TABLE IF EXISTS tasks;

CREATE TABLE tasks (
    id VARCHAR(32) PRIMARY KEY,
    title VARCHAR(255) NOT NULL.
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP MOT NULL DEFAULT NOW()
);
