// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ManuelP84/calendar/business/task/usecase"
	"github.com/ManuelP84/calendar/infra/app"
	"github.com/ManuelP84/calendar/infra/http/server"
	"github.com/ManuelP84/calendar/infra/postgres"
)

// Injectors from wire.go:

func CreateApp() *app.App {
	engine := server.NewWebServer()
	appSettings := app.GetAppSettings()
	postgresDbSettings := app.GetPostgresBdSettings()
	postgresRepository := postgres.NewPostgresRepository(postgresDbSettings)
	taskUsecases := usecase.NewTaskUsecases(postgresRepository)
	appApp := app.NewApp(engine, appSettings, taskUsecases)
	return appApp
}
