// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ManuelP84/calendar/infra/app"
	"github.com/ManuelP84/calendar/infra/http/server"
)

// Injectors from wire.go:

func CreateApp() *app.App {
	engine := server.NewWebServer()
	appSettings := app.GetAppSettings()
	appApp := app.NewApp(engine, appSettings)
	return appApp
}
