// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TaskBus is an autogenerated mock type for the TaskBus type
type TaskBus struct {
	mock.Mock
}

// Publish provides a mock function with given fields: mssge
func (_m *TaskBus) Publish(mssge string) error {
	ret := _m.Called(mssge)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(mssge)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTaskBus interface {
	mock.TestingT
	Cleanup(func())
}

// NewTaskBus creates a new instance of TaskBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTaskBus(t mockConstructorTestingTNewTaskBus) *TaskBus {
	mock := &TaskBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
